### ISSUE TITLE
Getting error with latest jQuery 3.1.1

### ISSUE THREAD

**Issue by ilearnio** [sachinchoolur/lightslider#286] opened 2016-10-24 10:37 UTC
Sometimes (not always) when I reload a page I'm getting this error http://take.ms/eKDLD. Maybe this is because the API for jQuery.fn.load (http://take.ms/efdUL) has changed and now it needs 3 parameters instead of just a callback.

**Comment by ilearnio** [comment] 2016-10-24 10:42
This is happens all the times if I just open a page in a new tab instead of pressing reload button.

**Comment by ilearnio** [comment] 2016-10-24 10:56
This can be easily fixed by changing 

```js
obj.find('img').load(function () {
```
to 
```js
obj.find('img').on('load', function () {
```

**Comment by davidtgq** [comment] 2016-10-24 21:09
Duplicate of https://github.com/sachinchoolur/lightslider/issues/248

It looks like @sachinchoolur's last activity was on October 14 so he probably hasn't seen this yet :( I'm eagerly awaiting this as well, the only reason I haven't upgraded to jQuery 3 yet.

**Comment by sachinchoolur** [comment] 2016-10-25 02:53
Hi Guys,
The issue has been fixed. Sorry for the delay

**Closed by sachinchoolur** 2016-10-25 02:53 UTC
